name: example
description: Flutter SurrealDB WebAssembly(WASM) package example
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_console_widget:
    path: flutter_console_widget
  surrealdb_wasm: ^1.0.0-beta.14+8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
