name: surrealdb_wasm
description: Flutter SurrealDB WebAssembly(WASM) package
version: 1.0.1
repository: https://github.com/limcheekin/surrealdb_wasm

environment:
  sdk: "^3.4.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  surrealdb_js: ^1.0.1+7

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  logger:
  very_good_analysis: ^6.0.0


flutter:
  assets:
    - assets/wasm/surrealdb/
