name: surrealdb_wasm
description: Flutter SurrealDB WebAssembly(WASM) package
version: 0.7.0+3
repository: https://github.com/limcheekin/surrealdb_wasm

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  assets:
    - assets/wasm/surrealdb/
