name: surrealdb_wasm
description: Flutter SurrealDB WebAssembly(WASM) package
version: 0.9.0
repository: https://github.com/limcheekin/surrealdb_wasm

environment:
  sdk: "^3.4.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  surrealdb_js: ^1.0.0-beta.14+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  logger:
  very_good_analysis: ^5.1.0


flutter:
  assets:
    - assets/wasm/surrealdb/
