name: surrealdb_wasm
description: Flutter surrealdb.wasm.
version: 0.0.1
homepage:

environment:
  sdk: ">=3.1.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/wasm/surrealdb/
