name: browser tests

on:
  push:
    branches: [main]
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout own repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter doctor -v

      - name: Check formatting
        run: dart format --line-length 80 --set-exit-if-changed lib integration_test

      - name: Analyze code
        run: flutter analyze lib integration_test

      - name: Run chrome driver
        run: |
          git clone https://github.com/Bdaya-Dev/web_installers --branch new-chromedriver-urls
          cd web_installers/packages/web_drivers
          dart pub get
          dart lib/web_driver_installer.dart chromedriver &

      - name: Run browser tests
        run: ./ci-integration-test.sh

      - name: Git Commit Integration Test Reports
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github@users.noreply.github.com"
          git add integration_test/reports
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "chore: added integration test reports"
            git push
          fi
