name: Build surrealdb.wasm and js files
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout own repo
        uses: actions/checkout@v4

      - name: "Checkout surrealdb.wasm repo (latest tag)"
        run: |
          git clone https://github.com/limcheekin/surrealdb.wasm.git
          #cd surrealdb.wasm;export LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          #git checkout $LATEST_TAG

      - name: "Install Node & NPM"
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"

      - name: "Install wasm-pack"
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: "Install surrealdb.wasm NPM dependencies"
        run: cd surrealdb.wasm;npm install

      - name: "Build"
        run: cd surrealdb.wasm;wasm-pack build --release --target web --out-name index --out-dir ../assets/wasm/surrealdb --no-default-features --features protocol-ws,protocol-http,kv-indxdb,kv-mem,rustls

      - name: "Install NPM dependencies"
        run: npm install

      - name: "Minify and compress JavaScript files"
        run: npm run package

      - name: "Compress wasm file"
        run: npm run compress-wasm

      - name: Git commit compressed surrealdb_wasm assets
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github@users.noreply.github.com"
          git add -f assets/wasm/surrealdb/surrealdb_wasm.*
          git add assets/wasm/surrealdb/index.js
          git add assets/wasm/surrealdb/index_bg.wasm
          git add assets/wasm/surrealdb/surrealdb.wasm.gz
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "chore: updated assets/wasm/surrealdb"
            git push
          fi
