name: publish
on:
  push:
    tags: # trigger the publish job on tag creation
      - "*"
jobs:
  test:
    uses: ./.github/workflows/browser-tests.yaml

  publish_github_release:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ncipollo/release-action@v1
        with:
          bodyFile: "RELEASE.md"

  publish_pub_dev:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter doctor -v

      - name: Update GITHUB_RUN_NUMBER to version
        run: ./update_version.sh

      - name: Publish package
        run: |
          mkdir -p ~/.config/dart
          echo ${{ secrets.CREDENTIAL_JSON }} > ~/.config/dart/pub-credentials.json
          flutter pub publish --dry-run
          flutter pub publish

      - name: Git commit the updated pubspec.yaml
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github@users.noreply.github.com"
          git add pubspec.yaml
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "chore: updated the version of pubspec.yaml"
            git push
          fi

  deploy:
    needs: publish_pub_dev
    uses: ./.github/workflows/deploy.yaml
