name: publish-draft
on:
  push:
    tags: # trigger the publish job on tag creation
      - "*"
jobs:
  test:
    uses: ./.github/workflows/browser-tests.yaml

  publish_github_release:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ncipollo/release-action@v1
        with:
          bodyFile: "RELEASE.md"

  publish_pub_dev:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Append GITHUB_RUN_NUMBER to version
        run: ./update_version.sh

      - name: Publish package
        uses: sakebook/actions-flutter-pub-publisher@v1.4.1
        with:
          credential: ${{ secrets.CREDENTIAL_JSON }}
          flutter_package: true
          skip_test: true
          dry_run: true

      - name: Git commit the updated pubspec.yaml
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github@users.noreply.github.com"
          git add pubspec.yaml
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "chore: updated the version of pubspec.yaml"
            git push
          fi

  deploy:
    needs: publish_pub_dev
    uses: ./.github/workflows/deploy.yaml
